apiVersion: apps/v1
kind: Deployment
metadata:
  name: madworld-grpc-deployment
  namespace: madworld
  labels:
    app: madworld-grpc
    name: backend-grpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: madworld-grpc
      task: backend-grpc
  template:
    metadata:
      labels:
        app: madworld-grpc
        task: backend-grpc
    spec:
      containers:
        - name: madworld-grpc
          image: rodero/madworld-grpc:latest
          args:
            - /server
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: madworld-grpc-loadbalancer
  namespace: madworld
spec:
  selector:
    app: madworld-grpc
    task: backend-grpc
  ports:
    - protocol: TCP
      name: http
      port: 8083
      targetPort: 8080
  type: LoadBalancer