apiVersion: v1
kind: Secret
metadata:
  name: madworld-secrets
  namespace: madworld
type: Opaque
data:
  dbpassword: NU9FT0w4bXVJS3BZSmNpR01nTXp6RU9zMHhraFRPc3NxaUtCVWZoN3VUbnpRNXN1N3E=
  jwtkey: M2tDNXgyVkxDdlY0aXZocGhyMmZDVWRuaHF1UWFQNVp5NGhqRFA0OVZwS3FtZ3hFUnY=
  seq_firsttime_password: UUpFTlRjZFAyYnlSZmdHcWEzZnhQUGFXb2hST2FqVGxjNXF5eHk2TjRMbFNqNitrd0xJT056aUZJcDExTHJERWhvcWJpbkl3clVaUVZicHZjTkpYcE5EZi9MUTdleGVmQ3R1elV1N1hKRzVT